title: "星尘点点"
owner: "ZhouJihao"
url: "https://warpprism.github.io"
baseurl: "https://warpprism.github.io"
email: "249662605@qq.com"
wechat: "zjhpswechat"
github_username: "WarpPrism"
description: "博客寄语：人生中有很多珍贵的东西，只是当它们唾手可得的时候，你不觉得珍贵。珍惜身边的一切，不要等失去了再后悔莫及。"
exclude: [node_modules, gulpfile.js, package.json, .gitignore]
debug_mode: true
highlighter: rouge
markdown: kramdown
kramdown:
    input: GFM
    syntax_highlighter: rouge
defaults:
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: post
            styles: [highlight.css, post.css]
